// GENERATED by npm run gee:generate. Edit data configuration and scripts/gee/pipeline.js.
// No satellite results have been generated by this local command.
var analysisMode = "current";
var runId = "current_87e2e1b42701";
var analysisConfig = {
  "schemaVersion": 1,
  "boundaryFile": "data/boundaries/mumbai-localities-v0.3.geojson",
  "boundaryVersion": "juhu-v0.3",
  "boundaryVersionMode": "per-locality",
  "boundaryFiles": {
    "mumbai-localities-v0.2": "data/boundaries/mumbai-localities-v0.2.geojson",
    "juhu-v0.3": "data/boundaries/mumbai-localities-v0.3.geojson"
  },
  "currentSeasonYear": 2025,
  "historicalSeasonYears": [
    2015,
    2020,
    2025
  ],
  "seasonStart": "11-01",
  "seasonEndExclusive": "03-01",
  "approvalFiles": [
    "data/calibration/andheri-approval-v1.json",
    "data/calibration/juhu-approval-v1.json"
  ],
  "greenThreshold": 0.3,
  "thresholdDecisionId": "juhu-sr-dry2026-v0.3-v1",
  "candidateThresholds": [
    0.2,
    0.25,
    0.3,
    0.35,
    0.4,
    0.45
  ],
  "cloudScoreMinimum": 0.6,
  "sceneCloudMaximum": 60,
  "minimumObservations": 3,
  "minimumCoveragePercent": 90,
  "waterNdwiThreshold": 0,
  "scaleMeters": 10,
  "crs": "EPSG:32643",
  "currentCollection": "COPERNICUS/S2_SR_HARMONIZED",
  "historicalCollection": "COPERNICUS/S2_HARMONIZED",
  "methodVersion": "level1-1.0",
  "waterMaskVersion": "ndwi-union-1.0",
  "targetLocalityId": "juhu",
  "thresholdApproved": true,
  "approvedThreshold": 0.3,
  "approvalStatus": "human-approved",
  "humanApproval": true,
  "approvalDate": "2026-09-23",
  "approvalTimezone": "Asia/Calcutta",
  "approvalSource": "Explicit project-owner approval in this task for Juhu v0.3 and the scoped two-locality beta publication workflow.",
  "calibrationVersion": "juhu-sr-dry2026-v0.3-v1",
  "methodologyVersion": "level1-1.0",
  "localityId": "juhu",
  "displayName": "Juhu",
  "kind": "current",
  "seasonYear": 2025,
  "dateStart": "2025-11-01",
  "dateEnd": "2026-03-01",
  "analysisStart": "2025-11-01",
  "analysisEnd": "2026-02-28",
  "analysisEndInclusive": "2026-02-28",
  "collection": "COPERNICUS/S2_SR_HARMONIZED",
  "dataset": "COPERNICUS/S2_SR_HARMONIZED",
  "boundaryConfidence": "medium",
  "boundarySha256": "2834e22d72c99e6bc27a1b465b5321405dd0deb10e83e5b2f4e54870d61b5bef",
  "referenceFile": "data/calibration/juhu-reference-areas-v0.3.geojson",
  "referenceSha256": "1f7dde0a2ee70b114c3a962f342f31b3915b4b90e3e7d678c70c0a6bcda100b4",
  "sceneCount": 51,
  "cloudMaskMethod": "Cloud Score+ cs_cdf >= 0.60; valid B2/B3/B4/B8 masks; median clear composite",
  "waterHandling": "Composite NDWI > 0 excluded from the observed-land denominator; coastline, beach transition and lagoon-edge samples were rejected during review.",
  "sensitivitySummary": {
    "threshold0.25Percent": 58.27182464132272,
    "threshold0.30Percent": 48.813276934442705,
    "threshold0.35Percent": 39.55104180284649,
    "spread0.25To0.35PercentagePoints": 18.72078283847623,
    "plausibleRange": "0.30-0.35"
  },
  "knownLimitations": [
    "The reviewed polygons are purposive image-reference samples, not field-verified ground truth.",
    "Ten-metre pixels mix vegetation and built surfaces, especially in low-rise residential fabric.",
    "The estimate is sensitive to threshold choice and is specific to this boundary, season, mask and calibration set.",
    "Beach, lagoon and aerodrome-edge areas were excluded from calibration evidence; residual coastal mixed-pixel effects may remain."
  ],
  "publishableRanking": false,
  "scopeNote": "Approval is specific to Juhu v0.3, the 2025-11-01 through 2026-02-28 window, this Sentinel-2 workflow and the reviewed v0.3 calibration samples. NDVI 0.30 is not a universal TreeScore threshold."
};
var boundaryGeoJson = {"type":"FeatureCollection","name":"mumbai-localities-v0.3","crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:OGC:1.3:CRS84"}},"features":[{"type":"Feature","properties":{"localityId":"juhu","name":"Juhu","parentLocality":"Juhu","city":"Mumbai","state":"Maharashtra","country":"India","boundaryVersion":"juhu-v0.3","boundaryType":"TreeScore-defined locality analysis area","isOfficialBoundary":false,"boundaryConfidence":"medium","measurementLabel":"Satellite-derived green cover estimate","methodNote":"Basemap-reviewed TreeScore analysis polygon corrected after the v0.2 real-data check exposed unintended aerodrome, lagoon and open-ground inclusion. Not an official administrative boundary.","sourceNote":"Preserves the v0.2 northern, main eastern and conservative coastal residential edges. The southern edge was retraced against satellite imagery around the north and west of the lagoon/aerodrome complex, retaining the coastal residential strip while excluding the lagoon, operational/open airport land, runway-side surfaces, excess beach/sea and adjacent Santacruz/Vile Parle fabric.","publicDisclaimer":"Locality boundaries are TreeScore-defined analysis areas, not official administrative boundaries."},"geometry":{"type":"Polygon","coordinates":[[[72.8255,19.117],[72.8305,19.1175],[72.835,19.1135],[72.836,19.106],[72.8358,19.1036],[72.8335,19.1033],[72.831,19.1034],[72.829,19.1033],[72.8285,19.101],[72.828,19.097],[72.8252,19.0965],[72.8245,19.105],[72.8248,19.112],[72.8255,19.117]]]}}]};
var referenceGeoJson = {"type":"FeatureCollection","features":[]};
// Executed ONLY in the Earth Engine Code Editor. Prefix generated by generate-gee.mjs.
// The same cloud/water/coverage functions drive calibration, current and historical runs.
var localities = ee.FeatureCollection(boundaryGeoJson);
var historical = analysisMode === 'historical' || analysisMode === 'calibration-historical';
var calibration = analysisMode.indexOf('calibration') === 0;
var exploration = analysisMode === 'andheri-test' || analysisMode === 'locality-test';
var collectionId = historical ? analysisConfig.historicalCollection : analysisConfig.currentCollection;
var years = historical ? analysisConfig.historicalSeasonYears : [analysisConfig.currentSeasonYear];
if (!calibration && !exploration && (typeof analysisConfig.greenThreshold !== 'number' || !analysisConfig.thresholdDecisionId)) {
  throw new Error('Calibration decision pending. Set greenThreshold and thresholdDecisionId in data/analysis-config.json, then regenerate.');
}
if (calibration && !referenceGeoJson.features.length) {
  throw new Error('Reference areas pending. Add field-reviewed green and built-up sample polygons to data/calibration/reference-areas.geojson, then regenerate.');
}
var qaCollection = ee.ImageCollection('GOOGLE/CLOUD_SCORE_PLUS/V1/S2_HARMONIZED');
function season(year) {
  var start = year + '-' + analysisConfig.seasonStart;
  var endYear = year + (analysisConfig.seasonEndExclusive <= analysisConfig.seasonStart ? 1 : 0);
  var end = endYear + '-' + analysisConfig.seasonEndExclusive;
  var scenes = ee.ImageCollection(collectionId).filterBounds(localities.geometry()).filterDate(start,end)
    .filter(ee.Filter.lte('CLOUDY_PIXEL_PERCENTAGE', analysisConfig.sceneCloudMaximum));
  var clear = scenes.linkCollection(qaCollection,['cs_cdf']).map(function(image) {
    // An unmatched QA image stays masked, never treated as clear sky.
    var mask = image.select('cs_cdf').gte(analysisConfig.cloudScoreMinimum)
      .and(image.select(['B2','B3','B4','B8']).mask().reduce(ee.Reducer.min()));
    return image.select(['B2','B3','B4','B8']).updateMask(mask);
  });
  // A masked seed preserves band names even when the archive has no observations.
  var seed = ee.Image.constant([0,0,0,0]).rename(['B2','B3','B4','B8']).updateMask(ee.Image.constant(0));
  var safe = clear.merge(ee.ImageCollection([seed]));
  var composite = safe.median();
  var red=composite.select('B4'), nir=composite.select('B8'), green=composite.select('B3');
  var ndvi=nir.subtract(red).divide(nir.add(red)).updateMask(nir.add(red).neq(0)).rename('NDVI');
  var ndwi=green.subtract(nir).divide(green.add(nir)).updateMask(green.add(nir).neq(0)).rename('NDWI');
  var valid=safe.select('B8').count().gte(analysisConfig.minimumObservations)
    .and(ndvi.mask()).and(ndwi.mask()).unmask(0);
  return {year:year,start:start,end:end,scenes:scenes,ndvi:ndvi,ndwi:ndwi,valid:valid,composite:composite};
}
var seasons=years.map(season);
// Historical comparisons use the intersection of adequately observed pixels and
// exclude the union of detected water across all years. Powai's hole is retained.
var commonValid=ee.ImageCollection(seasons.map(function(s){return s.valid;})).min();
var waterUnion=ee.ImageCollection(seasons.map(function(s){return s.ndwi.gt(analysisConfig.waterNdwiThreshold).unmask(0);})).max();
var potentialLand=waterUnion.not();
var analysisLand=potentialLand.and(commonValid);
var pixelArea=ee.Image.pixelArea();
function sumArea(mask,geometry) {
  var result=pixelArea.multiply(mask.unmask(0)).rename('area').reduceRegion({
    reducer:ee.Reducer.sum(),geometry:geometry,crs:analysisConfig.crs,scale:analysisConfig.scaleMeters,maxPixels:1e8,tileScale:4
  }).get('area');
  return ee.Number(ee.Algorithms.If(result,result,0));
}
function stats(feature,s,threshold) {
  var geometry=feature.geometry();
  var land=sumArea(analysisLand,geometry);
  var possible=sumArea(potentialLand,geometry);
  var green=sumArea(analysisLand.and(s.ndvi.gte(threshold).unmask(0)),geometry);
  var coverage=ee.Number(ee.Algorithms.If(possible.gt(0),land.divide(possible).multiply(100),0));
  var count=s.scenes.filterBounds(geometry).size();
  var valid=land.gt(0).and(coverage.gte(analysisConfig.minimumCoveragePercent)).and(count.gte(analysisConfig.minimumObservations));
  return ee.Feature(null,{
    localityId:feature.get('localityId'),kind:historical?'historical':'current',seasonYear:s.year,
    greenCoverPercent:ee.Algorithms.If(valid,green.divide(land).multiply(100),-1),
    analysisAreaSqKm:land.divide(1e6),greenAreaSqKm:green.divide(1e6),polygonAreaSqKm:geometry.area(1).divide(1e6),
    coveragePercent:coverage,imageCount:count,threshold:threshold,
    thresholdDecisionId:analysisConfig.thresholdDecisionId || 'UNREVIEWED',
    dateStart:s.start,dateEnd:s.end,collection:collectionId,
    metric:'Satellite-derived green cover estimate',methodVersion:analysisConfig.methodVersion,
    boundaryVersion:feature.get('boundaryVersion'),waterMaskVersion:analysisConfig.waterMaskVersion,
    denominatorId:runId + (historical?'-common-land':'-observed-land'),
    cloudScoreMinimum:analysisConfig.cloudScoreMinimum,sceneCloudMaximum:analysisConfig.sceneCloudMaximum,
    minimumObservations:analysisConfig.minimumObservations,minimumCoveragePercent:analysisConfig.minimumCoveragePercent,
    waterNdwiThreshold:analysisConfig.waterNdwiThreshold,crs:analysisConfig.crs,scaleMeters:analysisConfig.scaleMeters,
    runId:runId,dataStatus:'calculated',publishableRanking:false,
    qualityStatus:ee.Algorithms.If(valid,'review-required','insufficient-coverage'),
    imageIds:s.scenes.filterBounds(geometry).aggregate_array('system:index').join(';'),
    localityName:feature.get('name'),validLandAreaSqKm:land.divide(1e6),sceneCount:count,
    analysisStart:s.start,analysisEnd:analysisConfig.analysisEndInclusive || s.end,
    methodologyVersion:analysisConfig.methodologyVersion || analysisConfig.methodVersion,
    calibrationVersion:analysisConfig.calibrationVersion || '',
    cloudMaskMethod:analysisConfig.cloudMaskMethod || '',
    referenceSha256:analysisConfig.referenceSha256 || '',
    reviewStatus:analysisConfig.approvalStatus || 'unreviewed'
  });
}
Map.centerObject(localities,exploration?14:12);
Map.addLayer(localities.style({color:'1f3a2d',fillColor:'00000000'}),{},'TreeScore-defined areas; not official');
Map.addLayer(analysisLand.selfMask(),{palette:['e3e9d9']},'Observed land denominator',false);
Map.addLayer(waterUnion.selfMask(),{palette:['3388aa']},'Excluded water union',false);
seasons.forEach(function(s) {
  Map.addLayer(s.composite.clip(localities.geometry()),{bands:['B4','B3','B2'],min:0,max:3000,gamma:1.2},s.year+'–'+(s.year+1)+' RGB',exploration);
  Map.addLayer(s.composite,{bands:['B8','B4','B3'],min:0,max:4000},s.year+' false colour',false);
  Map.addLayer(s.ndvi.updateMask(analysisLand).clip(localities.geometry()),{min:-0.2,max:0.8,palette:['c8b99b','fbf9f2','1f3a2d']},s.year+' NDVI',!exploration);
  print(s.year+' candidate scene count',s.scenes.size());
});
if(exploration) {
  var testSeason=seasons[0];
  var testFeature=ee.Feature(localities.first());
  var testLocalityId=analysisConfig.targetLocalityId || testFeature.get('localityId');
  var testLocalityName=testFeature.get('name');
  print('EXPLORATORY ONLY — no final threshold; no production import', {
    localityId:testLocalityId,localityName:testLocalityName,dateStart:testSeason.start,dateEndExclusive:testSeason.end,
    collection:collectionId,cloudMask:'Cloud Score+ cs_cdf >= '+analysisConfig.cloudScoreMinimum,
    minimumClearObservations:analysisConfig.minimumObservations,
    note:'TreeScore-defined analysis area, not an official administrative boundary.'
  });
  print('Scene IDs after date/bounds/scene-cloud filtering',testSeason.scenes.aggregate_array('system:index'));
  print('TreeScore polygon area (sq km)',testFeature.geometry().area(1).divide(1e6));
  print('Area with sufficient valid observations, before water exclusion (sq km)',sumArea(commonValid,testFeature.geometry()).divide(1e6));
  print('Excluded water within polygon (sq km)',sumArea(waterUnion.and(commonValid),testFeature.geometry()).divide(1e6));
  print('Valid observed land after water exclusion (sq km)',sumArea(analysisLand,testFeature.geometry()).divide(1e6));
  var candidateRows=ee.FeatureCollection(analysisConfig.candidateThresholds.map(function(threshold) {
    Map.addLayer(testSeason.ndvi.gte(threshold).updateMask(analysisLand).selfMask().clip(testFeature.geometry()),
      {palette:['32b45d']},'Candidate NDVI >= '+threshold.toFixed(2)+' — NOT FINAL',false);
    return stats(testFeature,testSeason,threshold).set({kind:'calibration',sampleName:ee.String('Whole ').cat(ee.String(testLocalityName)).cat(' sensitivity test'),sampleType:'unlabelled',observation:'Visual exploration only; not ground-truth calibration'});
  }));
  print('Candidate threshold sensitivity — same valid-land denominator',candidateRows.select(['threshold','greenCoverPercent','greenAreaSqKm','analysisAreaSqKm','coveragePercent','imageCount','qualityStatus']));
  Export.table.toDrive({collection:candidateRows,description:'treescore_'+String(testLocalityId).replace(/-/g,'_')+'_candidates_'+runId,fileFormat:'CSV'});
  // Uses the existing importer schema only after an explicit documented decision.
  // Both values remain null in the generated first-run script.
  if(typeof analysisConfig.greenThreshold==='number' && analysisConfig.thresholdDecisionId) {
    Export.table.toDrive({collection:ee.FeatureCollection([stats(testFeature,testSeason,analysisConfig.greenThreshold)]),description:'treescore_'+String(testLocalityId).replace(/-/g,'_')+'_review_required_'+runId,fileFormat:'CSV'});
  }
  print('Layer inspection: RGB first; toggle NDVI, then one candidate mask at a time. Do not infer a final threshold from appearance alone.');
} else if(calibration) {
  var references=ee.FeatureCollection(referenceGeoJson.features.map(function(f) {
    return ee.Feature(ee.Geometry.Polygon(f.geometry.coordinates,null,false),f.properties);
  }));
  print('Sample NDVI distributions',ui.Chart.image.histogram(seasons[0].ndvi.updateMask(analysisLand),references.geometry(),10,40));
  var calibrationRows=ee.FeatureCollection(seasons.map(function(s) {
    return ee.FeatureCollection(analysisConfig.candidateThresholds.map(function(threshold) {
    return references.map(function(f) {
      var row=stats(f,s,threshold);
      var distribution=s.ndvi.updateMask(analysisLand).reduceRegion({reducer:ee.Reducer.percentile([10,50,90]),geometry:f.geometry(),scale:10,crs:analysisConfig.crs,maxPixels:1e7});
      var sampleArea=sumArea(ee.Image.constant(1),f.geometry());
      var classifiedArea=ee.Number(row.get('greenAreaSqKm')).multiply(1e6);
      return row.set(distribution).set({kind:'calibration',sampleId:f.get('sampleId'),sampleName:f.get('sampleName'),sampleClass:f.get('sampleClass'),expectedType:f.get('expectedType'),reviewStatus:f.get('reviewStatus'),sampleType:f.get('sampleType'),observation:f.get('observation'),sampleArea:sampleArea,classifiedGreenArea:classifiedArea,classifiedGreenPercent:classifiedArea.divide(sampleArea).multiply(100),greenPercent:row.get('greenCoverPercent')});
    });
    })).flatten();
  })).flatten();
  print('Candidate thresholds — review against held-out samples',calibrationRows);
  Map.addLayer(references.style({color:'c99b5f',fillColor:'00000000'}),{},'Reviewed reference areas');
  Export.table.toDrive({collection:calibrationRows,description:'treescore_calibration_'+runId,fileFormat:'CSV'});
} else {
  var results=ee.FeatureCollection(seasons.map(function(s) {
    return localities.map(function(f){return stats(f,s,analysisConfig.greenThreshold);});
  })).flatten();
  print('Calculated estimates — not reviewed or publishable',results);
  print('Final CSV download',results.getDownloadURL({format:'CSV',filename:'treescore_'+String(analysisConfig.targetLocalityId || 'release').replace(/-/g,'_')+'_2025-11_2026-02_v1'}));
  Export.table.toDrive({collection:results,description:'treescore_'+analysisMode+'_'+runId,fileFormat:'CSV'});
}
