import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { validDate } from "../src/lib/metrics.ts";
const config = JSON.parse(readFileSync("data/analysis-config.json", "utf8"));
const boundaries = JSON.parse(readFileSync(config.boundaryFile, "utf8"));
const andheriTest = process.argv.includes("--andheri-test");
const localityArgument = process.argv.find((value) =>
  value.startsWith("--locality="),
);
const calibrationMode = process.argv.includes("--calibration");
const approvedMode = process.argv.includes("--approved");
const referencesArgument = process.argv.find((value) =>
  value.startsWith("--references="),
);
const targetLocalityId = andheriTest
  ? "andheri-west-core"
  : localityArgument?.slice("--locality=".length);
if (targetLocalityId) {
  boundaries.features = boundaries.features.filter(
    (f) => f.properties.localityId === targetLocalityId,
  );
  if (boundaries.features.length !== 1)
    throw new Error(
      `Expected exactly one active boundary for ${targetLocalityId}`,
    );
  config.boundaryVersion = boundaries.features[0].properties.boundaryVersion;
  config.currentCollection = "COPERNICUS/S2_SR_HARMONIZED";
  config.currentSeasonYear = 2025;
  config.seasonStart = "11-01";
  config.seasonEndExclusive = "03-01";
  config.greenThreshold = null;
  config.thresholdDecisionId = null;
  config.targetLocalityId = targetLocalityId;
  if (approvedMode) {
    const approvalPath = config.approvalFiles.find((path) => {
      const approval = JSON.parse(readFileSync(path, "utf8"));
      return approval.localityId === targetLocalityId;
    });
    if (!approvalPath)
      throw new Error(`No approval record configured for ${targetLocalityId}`);
    const approval = JSON.parse(readFileSync(approvalPath, "utf8"));
    if (
      approval.thresholdApproved !== true ||
      approval.approvalStatus !== "human-approved"
    )
      throw new Error(`Approval is incomplete for ${targetLocalityId}`);
    Object.assign(config, approval, {
      greenThreshold: approval.approvedThreshold,
      thresholdDecisionId: approval.thresholdDecisionId,
    });
  }
}
let references = JSON.parse(
  readFileSync(
    referencesArgument?.slice("--references=".length) ??
      "data/calibration/reference-areas.geojson",
    "utf8",
  ),
);
if (targetLocalityId)
  references = {
    ...references,
    features: references.features.filter(
      (f) => f.properties.localityId === targetLocalityId,
    ),
  };
const body = readFileSync("scripts/gee/pipeline.js", "utf8");
if (
  !validDate("2024-" + config.seasonStart) ||
  !validDate("2024-" + config.seasonEndExclusive)
)
  throw new Error(
    "Use valid MM-DD season dates; document any change to the November–February protocol.",
  );
if (
  config.greenThreshold !== null &&
  (typeof config.greenThreshold !== "number" ||
    config.greenThreshold < -1 ||
    config.greenThreshold > 1)
)
  throw new Error("Invalid threshold");
for (const f of references.features) {
  if (
    f.geometry?.type !== "Polygon" ||
    !f.properties?.sampleName ||
    !["green", "built-up", "mixed"].includes(f.properties.sampleType) ||
    !f.properties.observation ||
    !boundaries.features.some(
      (b) => b.properties.localityId === f.properties.localityId,
    )
  )
    throw new Error(
      "Reference samples need Polygon, localityId, sampleName, sampleType (green/built-up/mixed), observation.",
    );
}
const hash = createHash("sha256")
  .update(JSON.stringify({ config, boundaries, references }) + body)
  .digest("hex")
  .slice(0, 12);
mkdirSync("gee", { recursive: true });
for (const mode of targetLocalityId
  ? [
      calibrationMode
        ? "calibration"
        : approvedMode
          ? "current"
        : andheriTest
          ? "andheri-test"
          : "locality-test",
    ]
  : ["calibration", "calibration-historical", "current", "historical"]) {
  const prefix = `// GENERATED by npm run gee:generate. Edit data configuration and scripts/gee/pipeline.js.\n// No satellite results have been generated by this local command.\nvar analysisMode = ${JSON.stringify(mode)};\nvar runId = ${JSON.stringify(mode + "_" + hash)};\nvar analysisConfig = ${JSON.stringify(config, null, 2)};\nvar boundaryGeoJson = ${JSON.stringify(boundaries)};\nvar referenceGeoJson = ${JSON.stringify(references)};\n`;
  const outputName = targetLocalityId
      ? calibrationMode
        ? `treescore-${targetLocalityId}-calibration.gee.js`
        : approvedMode
          ? `treescore-${targetLocalityId}-final-export.gee.js`
        : targetLocalityId === "andheri-west-core" && andheriTest
        ? "treescore-andheri-test.gee.js"
        : `treescore-${targetLocalityId}-browser-run.gee.js`
    : `treescore-${mode}.gee.js`;
  writeFileSync(`gee/${outputName}`, prefix + body);
}
console.log(
  "Generated self-contained Earth Engine scripts. Calibration samples and threshold decision remain external work.",
);
